---

data_path: "./data/consumer.csv" #if consumer.csv : input_dim = 16
federated: true #true if you want to run the federated version, false if the centralized one
input_dim: 16

train_ratio: 0.8
val_ratio: 0.1

num_rounds: 10
num_clients: 2
batch_size: 20
num_classes: 2
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2
num_epochs: 10
config_fit:
  lr: 0.001
  local_epochs: 1


defaults:
  - model: binaryNet
  - strategy: fedavg 
  - optimizer: adam

partition_dataset:
  _target_: data.partition_dataset
  _partial_: true
  batch_size: ${batch_size}
  val_ratio: ${val_ratio}

load_dataset: 
  _target_: data.load_dataset
  data_path: ${data_path}
  train_ratio: ${train_ratio}
  federated: ${federated}