---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

federated: True
num_clients: 2
num_epochs: 1
batch_size: 32
clients_per_round: 2
learning_rate: 0.01
num_rounds: 50
mu: 0.01
partitioning: "uniform"
dataset_path: "./data/mv.csv"
dataset_seed: 42
alpha: 0.5
labels_per_client: 2 # only used when partitioning is label quantity
momentum: 0.9
weight_decay: 0.00001

client_fn:
  _target_: client_fedprox.gen_client_fn
  _recursive_: False
  proximal_mu: ${mu}
  num_epochs: ${num_epochs}
  learning_rate: ${learning_rate}
  momentum: ${momentum}
  weight_decay: ${weight_decay}

dataset:
  # dataset config
  path: ${dataset_path}
  partitioning: ${partitioning}
  batch_size: ${batch_size} # batch_size = batch_size_ratio * total_local_data_size
  train_split: 0.8
  val_split: 0.1
  seed: ${dataset_seed}
  alpha: ${alpha}
  labels_per_client: ${labels_per_client}

model:
  # model config
  _target_: model.BinaryNet
  input_dim: 14 #16 if consumer, 14 if mv
  num_classes: 2

strategy:
  _target_: flwr.server.strategy.FedAvg # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  fraction_fit: 0.00001 # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:
  # client config

server_device: cpu

client_resources:
  num_cpus: 4
  num_gpus: 0.0